//go:build generate

package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

func main() {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	buf.WriteString("package main\n\n")

	unknownFG := rgbColor{R: 255, G: 120, B: 0}
	unknownBG := rgbColor{R: 255, G: 255, B: 255}
	fmt.Fprintf(&buf, "var unknownTagStyle = resolvedTagStyle{FG: rgbColor{R: %d, G: %d, B: %d}, BG: rgbColor{R: %d, G: %d, B: %d}, Prefix: %q}\n\n",
		unknownFG.R, unknownFG.G, unknownFG.B, unknownBG.R, unknownBG.G, unknownBG.B, ansiPrefix(unknownFG, unknownBG))

	type resolvedEntry struct {
		name string
		fg   rgbColor
		bg   rgbColor
	}

	var entries []resolvedEntry
	for _, style := range tagStyles {
		bg := mustColor(style.BG)
		fg := foregroundFor(bg, style.FG)
		for _, name := range style.Names {
			entries = append(entries, resolvedEntry{
				name: strings.ToLower(name),
				fg:   fg,
				bg:   bg,
			})
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})

	buf.WriteString("var resolvedTagStyles = map[string]resolvedTagStyle{\n")
	for _, entry := range entries {
		fmt.Fprintf(&buf, "\t%q: {FG: rgbColor{R: %d, G: %d, B: %d}, BG: rgbColor{R: %d, G: %d, B: %d}, Prefix: %q},\n",
			entry.name,
			entry.fg.R, entry.fg.G, entry.fg.B,
			entry.bg.R, entry.bg.G, entry.bg.B,
			ansiPrefix(entry.fg, entry.bg))
	}
	buf.WriteString("}\n")

	if err := os.WriteFile("styles_gen.go", buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write styles_gen.go: %v\n", err)
		os.Exit(1)
	}
	if output, err := exec.Command("gofmt", "-w", "styles_gen.go").CombinedOutput(); err != nil {
		fmt.Fprintf(os.Stderr, "gofmt styles_gen.go: %v\n%s", err, output)
		os.Exit(1)
	}
}

func ansiPrefix(fg, bg rgbColor) string {
	return fmt.Sprintf("\x1b[1m\x1b[38;2;%d;%d;%dm\x1b[48;2;%d;%d;%dm", fg.R, fg.G, fg.B, bg.R, bg.G, bg.B)
}
